"""nucleo bancario: accounts, ledger, idempotency

Revision ID: 0b9749d7523d
Revises: 
Create Date: 2026-08-04 07:58:23.290417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0b9749d7523d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.String(length=16), nullable=False),
    sa.Column('balance', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_type = 'EXTERNAL' OR balance >= 0", name='ck_accounts_balance_non_negative'),
    sa.CheckConstraint("account_type IN ('BROKER', 'PLATFORM', 'EXTERNAL')", name='ck_accounts_valid_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_accounts_singleton_system_types', 'accounts', ['account_type'], unique=True, postgresql_where=sa.text("account_type IN ('PLATFORM', 'EXTERNAL')"))
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=120), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('movement_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('operation_type', sa.String(length=24), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("operation_type IN ('DEPOSIT', 'TRANSFER', 'COMMISSION_SPLIT')", name='ck_ledger_valid_operation_type'),
    sa.CheckConstraint('amount <> 0', name='ck_ledger_amount_not_zero'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_entries_account_id_created_at', 'ledger_entries', ['account_id', 'created_at'], unique=False)
    op.create_index('ix_ledger_entries_movement_id', 'ledger_entries', ['movement_id'], unique=False)
    # ### end Alembic commands ###

    # --------------------------------------------------------------------
    # APPEND-ONLY POR TRIGGER
    #
    # Que el ledger sea inmutable no puede depender de que nadie escriba un
    # UPDATE por error, ni de un ORM, ni de una convencion de equipo. Postgres
    # aborta cualquier UPDATE o DELETE sobre ledger_entries, venga de la app,
    # de una migracion futura o de un psql a mano en produccion.
    #
    # Corregir un asiento equivocado se hace como en contabilidad de verdad:
    # con un asiento de reversion, no borrando la historia.
    # --------------------------------------------------------------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION ledger_entries_append_only()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION
                'ledger_entries es append-only: % no esta permitido. Reversa con un asiento nuevo.',
                TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_ledger_entries_append_only
        BEFORE UPDATE OR DELETE ON ledger_entries
        FOR EACH ROW EXECUTE FUNCTION ledger_entries_append_only();
        """
    )

    # --------------------------------------------------------------------
    # CUENTAS DE SISTEMA
    #
    # UUIDs fijos y conocidos (ver app/modules/accounts/constants.py): el sistema
    # necesita poder nombrar "la plataforma" y "el mundo exterior" sin buscarlas
    # por nombre ni depender del orden de creacion.
    #
    # La cuenta EXTERNAL arranca en 0 y se hunde en negativo con cada deposito.
    # Su saldo, cambiado de signo, es el total de plata viva dentro del sistema.
    # --------------------------------------------------------------------
    op.execute(
        """
        INSERT INTO accounts (id, name, account_type, balance)
        VALUES
            ('00000000-0000-0000-0000-000000000001', 'Plataforma', 'PLATFORM', 0),
            ('00000000-0000-0000-0000-000000000002', 'Mundo exterior', 'EXTERNAL', 0);
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_ledger_entries_append_only ON ledger_entries;")
    op.execute("DROP FUNCTION IF EXISTS ledger_entries_append_only();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ledger_entries_movement_id', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_account_id_created_at', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('idempotency_keys')
    op.drop_index('uq_accounts_singleton_system_types', table_name='accounts', postgresql_where=sa.text("account_type IN ('PLATFORM', 'EXTERNAL')"))
    op.drop_table('accounts')
    # ### end Alembic commands ###
