"""listings y motor de comisiones

Revision ID: 9e5e6444c341
Revises: 0b9749d7523d
Create Date: 2026-08-04 08:36:33.954821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9e5e6444c341'
down_revision: Union[str, None] = '0b9749d7523d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('listing_broker_account_id', sa.UUID(), nullable=False),
    sa.Column('listing_broker_bps', sa.Integer(), nullable=False),
    sa.Column('selling_broker_bps', sa.Integer(), nullable=False),
    sa.Column('platform_bps', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('listing_broker_bps + selling_broker_bps + platform_bps = 10000', name='ck_listings_bps_sum_to_total'),
    sa.CheckConstraint('listing_broker_bps >= 0 AND selling_broker_bps >= 0 AND platform_bps >= 0', name='ck_listings_bps_non_negative'),
    sa.ForeignKeyConstraint(['listing_broker_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('reported_by_account_id', sa.UUID(), nullable=False),
    sa.Column('selling_broker_account_id', sa.UUID(), nullable=False),
    sa.Column('listing_broker_account_id', sa.UUID(), nullable=False),
    sa.Column('gross_amount', sa.BigInteger(), nullable=False),
    sa.Column('listing_broker_bps', sa.Integer(), nullable=False),
    sa.Column('selling_broker_bps', sa.Integer(), nullable=False),
    sa.Column('platform_bps', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('listing_broker_share', sa.BigInteger(), nullable=True),
    sa.Column('selling_broker_share', sa.BigInteger(), nullable=True),
    sa.Column('platform_share', sa.BigInteger(), nullable=True),
    sa.Column('movement_id', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.String(length=120), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'EXECUTED' OR ( listing_broker_share IS NOT NULL AND selling_broker_share IS NOT NULL AND platform_share IS NOT NULL)", name='ck_commissions_executed_has_shares'),
    sa.CheckConstraint("status IN ('PENDING', 'EXECUTED', 'REJECTED')", name='ck_commissions_valid_status'),
    sa.CheckConstraint('gross_amount > 0', name='ck_commissions_gross_positive'),
    sa.CheckConstraint('listing_broker_bps + selling_broker_bps + platform_bps = 10000', name='ck_commissions_bps_sum_to_total'),
    sa.ForeignKeyConstraint(['listing_broker_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['reported_by_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['selling_broker_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commissions_listing_id', 'commissions', ['listing_id'], unique=False)
    op.create_index('ix_commissions_status', 'commissions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_commissions_status', table_name='commissions')
    op.drop_index('ix_commissions_listing_id', table_name='commissions')
    op.drop_table('commissions')
    op.drop_table('listings')
    # ### end Alembic commands ###
