"""indice para mis comisiones por broker que reporta

Revision ID: a82149a205ca
Revises: ebb77ceb84de
Create Date: 2026-08-05 03:49:03.666082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a82149a205ca'
down_revision: Union[str, None] = 'ebb77ceb84de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_commissions_reported_by_created_at', 'commissions', ['reported_by_account_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_commissions_reported_by_created_at', table_name='commissions')
    # ### end Alembic commands ###
